export enum weatherDetails {
    CLOUD = 'cloud',
    HUMIDITY = 'humidity',
    WIND = 'wind_mph'
}

export enum weatherConditions {
    SUNNY =  'Sunny',
    CLEAR = 'Clear',
    PARTLY_CLOUDY = 'Partly cloudy',
    CLOUDY = 'Cloudy',
    OVERCAST = 'Overcast',
    MIST = 'Mist',
    PATCHY_RAIN_POSSILE = 'Patchy rain possible',
    PATCHY_SNOW_POSSILE = 'Patchy snow possible',
    PATCHY_SLEET_POSSILE = 'Patchy sleet possible',
    PATCHY_FREEZING_DRIZZLE_POSSILE = 'Patchy freezing drizzle possible',
    THUNDERY_OUTBREAKS_POSSILE = 'Thundery outbreaks possible',
    BLOWING_SNOW = 'Blowing snow',
    BLIZZARD = 'Blizzard',
    FOG = 'Fog',
    FREEZING_FOG = 'Freezing fog',
    PATCHY_LIGHT_DRIZZLE = 'Patchy light drizzle',
    LIGHT_DRIZZLE = 'Light drizzle',
    FREEZING_DRIZZLE = 'Freezing drizzle',
    HEAVY_FREEZING_DRIZZLE = 'Heavy freezing drizzle',
    PATCHY_LIGHT_RAIN = 'Patchy light rain',
    LIGHT_RAIN = 'Light rain',
    MODERATE_RAIN_AT_A_TIMES = 'Moderate rain at times',
    MODERATE_RAIN = 'Moderate rain at times',
    HEAVY_RAIN_AT_A_TIMES = 'Heavy rain at times',
    HEAVY_RAIN = 'Heavy rain at times',
    LIGHT_FREEZING_RAIN = 'Light freezing rain',
    MODERATE_OR_HEAVY_FREEZING_RAIN = 'Moderate or heavy freezing rain',
    LIGHT_SLEET = 'Light sleet',
    MODERATE_OR_HEAVY_SLEET = 'Moderate or heavy sleet',
    PATCHY_LIGHT_SNOW = 'Patchy light snow',
    LIGHT_SNOW = 'Light snow',
    PATCHY_MODERATE_SNOW = 'Patchy moderate snow',
    MODERATE_SNOW = 'Moderate snow',
    PATCHY_HEAVY_SNOW = 'Patchy heavy snow',
    HEAVY_SNOW = 'Heavy snow',
    ICE_PALLETS = 'Ice pellets',
    LIGHT_RAIN_SHOWER = 'Light rain shower',
    MODERATE_OR_HEAVY_RAIN_SHOWER = 'Moderate or heavy rain shower',
    TORRENTIAL_RAIN_SHOWER = 'Torrential rain shower',
    LIGHT_SLEET_SHOWER = 'Light sleet showers',
    MODERATE_OR_HEAVY_SLEET_SHOWER = 'Moderate or heavy sleet showers',
    LIGHT_SNOW_SHOWER = 'Light snow showers',
    MODERATE_OR_HEAVY_SNOW_SHOWER = 'Moderate or heavy snow showers',
    LIGHT_SHOWERS_OF_ICE_PALLETS = 'Light showers of ice pellets',
    MODERATE_OR_HEAVY_SHOWERS_OF_ICE_PALLETS = 'Moderate or heavy showers of ice pellets',
    PATCHY_LIGHT_RAIN_WITH_THUNDER = 'Patchy light rain with thunder',
    MODERATE_OR_HEAVY_LIGHT_RAIN_WITH_THUNDER = 'Moderate or heavy rain with thunder',
    PATCHY_LIGHT_SNOW_WITH_THUNDER = 'Patchy light snow with thunder',
    MODERATE_OR_HEAVY_LIGHT_SNOW_WITH_THUNDER = 'Patchy light snow with thunder',

    
}

export enum weatherBackground {
    SUNNY =  'src/assets/images/sunny-sky.jpg',
    CLEAR = 'src/assets/images/clear-sky.jpg',
    PARTLY_CLOUDY_DAY= 'src/assets/images/partly-cloud-day.jpg',
    PARTLY_CLOUDY_NIGHT= 'src/assets/images/partly-cloud-night.jpg',
    CLOUDY_SKY= 'src/assets/images/partly-cloudy-sky.jpg',
    CLOUDY_NIGHT= 'src/assets/images/partly-cloudy-night.jpg',
    OVERCAST_SKY = 'src/assets/images/overcast-sky.jpg',
    OVERCAST_NIGHT = 'src/assets/images/overcast-night.jpg',
    MIST = 'src/assets/images/mist.jpg',
    MIST_NIGHT = 'src/assets/images/mist-night.jpg',
    PATCHY_RAIN_MORNING = 'src/assets/images/patchy-rain-morn.jpg',
    PATCHY_RAIN_NIGHT = 'src/assets/images/patchy-rain-night.jpg',
    PATCHY_SLEET_MORNING = 'src/assets/images/patchy-sleet-morn.jpg',
    PATCHY_SLEET_NIGHT = 'src/assets/images/patchy-sleet-night.jpg',
    THUNDERY_OUTBREAKS_MORNING = 'src/assets/images/thundery-outbreaks-morn.jpg',
    THUNDERY_OUTBREAKS_NIGHT = 'src/assets/images/thundery-outbreaks-night.jpg',
    BLOWING_SNOW_MORNING = 'src/assets/images/blowing-snow-morn.jpg',
    BLOWING_SNOW_NIGHT = 'src/assets/images/blowing-snow-night.jpg',
    BLIZZARD_MORNING = 'src/assets/images/blizzard-morn.jpg',
    BLIZZARD_NIGHT = 'src/assets/images/blizzard-night.jpg',
    FOG_MORNING = 'src/assets/images/fog-morn.jpg',
    FOG_NIGHT = 'src/assets/images/fog-night.jpg',
    FREEZING_FOG_MORNING = 'src/assets/images/freezing-fog-morn.jpg',
    FREEZING_FOG_NIGHT = 'src/assets/images/freezing-fog-night.jpg',
    PATCHY_LIGHT_DRIZZLE_MORNING = 'src/assets/images/patchy-light-drizzle-morn.jpg',
    PATCHY_LIGHT_DRIZZLE_NIGHT = 'src/assets/images/patchy-light-drizzle-night.jpg',     
    LIGHT_RAIN_MORNING = 'src/assets/images/lightrain-morn.jpg',
    LIGHT_RAIN_NIGHT = 'src/assets/images/lightrain-night.jpg',     
    HEAVY_RAIN_MORNING = 'src/assets/images/heavy-rain-morn.jpg',
    HEAVY_RAIN_NIGHT = 'src/assets/images/heavy-rain-night.jpg',   
    SLEET_MORNING = 'src/assets/images/sleet-morn.jpg',
    SLEET_NIGHT = 'src/assets/images/sleet-night.jpg',   
    SNOW_MORNING = 'src/assets/images/snow-morn.jpg',
    SNOW_NIGHT = 'src/assets/images/snow-night.jpg',  
    ICE_PALLETS_MORNING =  'src/assets/images/ice-pallets-morn.jpg',
    ICE_PALLETS_NIGHT =  'src/assets/images/ice-pallets-night.jpg',
    RAIN_SHOWER_MORNING =  'src/assets/images/rain-shower-morn.jpg',
    RAIN_SHOWER_NIGHT =  'src/assets/images/rain-shower-night.jpg',
    LIGHT_RAIN_WITH_THUNDER_MORN_NIGHT = 'src/assets/images/thunder.jpg',
    RAIN_SNOW_WITH_THUNDER_MORNING = 'src/assets/images/thundery-outbreaks-morn.jpg',
    RAIN_SNOW_WITH_THUNDER_NIGHT = 'src/assets/images/thundery-outbreaks-night.jpg'
}

export const WEATHER_DETAILS = [
    {id: 1, label: 'Cloudy', value: weatherDetails.CLOUD},
    {id: 2, label: 'Humidity', value: weatherDetails.HUMIDITY},
    {id: 3, label: 'Wind', value: weatherDetails.WIND}
]

export const WEATHER_BACKGROUND = [
    {id: 1, condition: weatherConditions.SUNNY, image: weatherBackground.SUNNY, is_day: 0},
    {id: 2, condition: weatherConditions.CLEAR, image: weatherBackground.CLEAR, is_day: 0},
    {id: 3, condition: weatherConditions.PARTLY_CLOUDY, image: weatherBackground.PARTLY_CLOUDY_DAY, is_day: 1},
    {id: 3, condition: weatherConditions.PARTLY_CLOUDY, image: weatherBackground.PARTLY_CLOUDY_NIGHT, is_day: 0},
    {id: 4, condition: weatherConditions.SUNNY, image: weatherBackground.SUNNY, is_day: 1},
    {id: 5, condition: weatherConditions.CLOUDY, image: weatherBackground.CLOUDY_SKY, is_day: 1},
    {id: 6, condition: weatherConditions.CLOUDY, image: weatherBackground.CLOUDY_NIGHT, is_day: 0},
    {id: 7, condition: weatherConditions.OVERCAST, image: weatherBackground.OVERCAST_SKY, is_day: 1},
    {id: 8, condition: weatherConditions.OVERCAST, image: weatherBackground.OVERCAST_NIGHT, is_day: 0},
    {id: 9, condition: weatherConditions.MIST, image: weatherBackground.MIST, is_day: 1},
    {id: 10, condition: weatherConditions.MIST, image: weatherBackground.MIST_NIGHT, is_day: 0},
    {id: 11, condition: weatherConditions.PATCHY_RAIN_POSSILE, image: weatherBackground.PATCHY_RAIN_MORNING, is_day: 1},
    {id: 12, condition: weatherConditions.PATCHY_RAIN_POSSILE, image: weatherBackground.PATCHY_RAIN_NIGHT, is_day: 0},
    {id: 13, condition: weatherConditions.PATCHY_SNOW_POSSILE, image: weatherBackground.SNOW_MORNING, is_day: 1},
    {id: 14, condition: weatherConditions.PATCHY_SNOW_POSSILE, image: weatherBackground.SNOW_NIGHT, is_day: 0},
    {id: 15, condition: weatherConditions.PATCHY_SLEET_POSSILE, image: weatherBackground.PATCHY_SLEET_MORNING, is_day: 1},
    {id: 16, condition: weatherConditions.PATCHY_SLEET_POSSILE, image: weatherBackground.PATCHY_SLEET_NIGHT, is_day: 0},
    {id: 17, condition: weatherConditions.PATCHY_FREEZING_DRIZZLE_POSSILE, image: weatherBackground.PATCHY_SLEET_MORNING, is_day: 1},
    {id: 18, condition: weatherConditions.PATCHY_FREEZING_DRIZZLE_POSSILE, image: weatherBackground.PATCHY_SLEET_NIGHT, is_day: 0},
    {id: 19, condition: weatherConditions.THUNDERY_OUTBREAKS_POSSILE, image: weatherBackground.THUNDERY_OUTBREAKS_MORNING, is_day: 1},
    {id: 20, condition: weatherConditions.THUNDERY_OUTBREAKS_POSSILE, image: weatherBackground.THUNDERY_OUTBREAKS_NIGHT, is_day: 0},
    {id: 21, condition: weatherConditions.BLOWING_SNOW, image: weatherBackground.BLOWING_SNOW_MORNING, is_day: 1},
    {id: 22, condition: weatherConditions.BLOWING_SNOW, image: weatherBackground.BLOWING_SNOW_NIGHT, is_day: 0},
    {id: 23, condition: weatherConditions.BLIZZARD, image: weatherBackground.BLIZZARD_MORNING, is_day: 1},
    {id: 24, condition: weatherConditions.BLIZZARD, image: weatherBackground.BLIZZARD_NIGHT, is_day: 0},
    {id: 25, condition: weatherConditions.FOG, image: weatherBackground.FOG_MORNING, is_day: 1},
    {id: 26, condition: weatherConditions.FOG, image: weatherBackground.FOG_NIGHT, is_day: 0},
    {id: 27, condition: weatherConditions.FREEZING_FOG, image: weatherBackground.FREEZING_FOG_MORNING, is_day: 1},
    {id: 28, condition: weatherConditions.FREEZING_FOG, image: weatherBackground.FREEZING_FOG_NIGHT, is_day: 0},
    {id: 29, condition: weatherConditions.PATCHY_LIGHT_DRIZZLE, image: weatherBackground.PATCHY_LIGHT_DRIZZLE_MORNING, is_day: 1},
    {id: 30, condition: weatherConditions.PATCHY_LIGHT_DRIZZLE, image: weatherBackground.PATCHY_LIGHT_DRIZZLE_NIGHT, is_day: 0},
    {id: 31, condition: weatherConditions.FREEZING_DRIZZLE, image: weatherBackground.BLOWING_SNOW_MORNING, is_day: 1},
    {id: 32, condition: weatherConditions.FREEZING_DRIZZLE, image: weatherBackground.BLOWING_SNOW_NIGHT, is_day: 0},
    {id: 33, condition: weatherConditions.HEAVY_FREEZING_DRIZZLE, image: weatherBackground.BLOWING_SNOW_MORNING, is_day: 1},
    {id: 34, condition: weatherConditions.HEAVY_FREEZING_DRIZZLE, image: weatherBackground.BLOWING_SNOW_NIGHT, is_day: 0},
    {id: 35, condition: weatherConditions.LIGHT_DRIZZLE, image: weatherBackground.PATCHY_LIGHT_DRIZZLE_MORNING, is_day: 1},
    {id: 36, condition: weatherConditions.LIGHT_DRIZZLE, image: weatherBackground.PATCHY_LIGHT_DRIZZLE_NIGHT, is_day: 0},
    {id: 37, condition: weatherConditions.PATCHY_LIGHT_RAIN, image: weatherBackground.PATCHY_RAIN_MORNING, is_day: 1},
    {id: 38, condition: weatherConditions.PATCHY_LIGHT_RAIN, image: weatherBackground.PATCHY_RAIN_NIGHT, is_day: 0},
    {id: 39, condition: weatherConditions.LIGHT_RAIN, image: weatherBackground.LIGHT_RAIN_MORNING, is_day: 1},
    {id: 40, condition: weatherConditions.LIGHT_RAIN, image: weatherBackground.LIGHT_RAIN_NIGHT, is_day: 0},
    {id: 41, condition: weatherConditions.MODERATE_RAIN_AT_A_TIMES, image: weatherBackground.LIGHT_RAIN_MORNING, is_day: 1},
    {id: 42, condition: weatherConditions.MODERATE_RAIN_AT_A_TIMES, image: weatherBackground.LIGHT_RAIN_NIGHT, is_day: 0},
    {id: 43, condition: weatherConditions.MODERATE_RAIN, image: weatherBackground.LIGHT_RAIN_MORNING, is_day: 1},
    {id: 44, condition: weatherConditions.MODERATE_RAIN, image: weatherBackground.LIGHT_RAIN_NIGHT, is_day: 0},
    {id: 45, condition: weatherConditions.HEAVY_RAIN_AT_A_TIMES, image: weatherBackground.HEAVY_RAIN_MORNING, is_day: 1},
    {id: 46, condition: weatherConditions.HEAVY_RAIN_AT_A_TIMES, image: weatherBackground.HEAVY_RAIN_NIGHT, is_day: 0},
    {id: 47, condition: weatherConditions.HEAVY_RAIN, image: weatherBackground.HEAVY_RAIN_MORNING, is_day: 1},
    {id: 48, condition: weatherConditions.HEAVY_RAIN, image: weatherBackground.HEAVY_RAIN_NIGHT, is_day: 0},
    {id: 49, condition: weatherConditions.LIGHT_FREEZING_RAIN, image: weatherBackground.LIGHT_RAIN_MORNING, is_day: 1},
    {id: 50, condition: weatherConditions.LIGHT_FREEZING_RAIN, image: weatherBackground.LIGHT_RAIN_NIGHT, is_day: 0},
    {id: 51, condition: weatherConditions.MODERATE_OR_HEAVY_FREEZING_RAIN, image: weatherBackground.LIGHT_RAIN_MORNING, is_day: 1},
    {id: 52, condition: weatherConditions.MODERATE_OR_HEAVY_FREEZING_RAIN, image: weatherBackground.LIGHT_RAIN_NIGHT, is_day: 0},
    {id: 53, condition: weatherConditions.LIGHT_SLEET, image: weatherBackground.SLEET_MORNING, is_day: 1},
    {id: 54, condition: weatherConditions.LIGHT_SLEET, image: weatherBackground.SLEET_NIGHT, is_day: 0},
    {id: 55, condition: weatherConditions.MODERATE_OR_HEAVY_SLEET, image: weatherBackground.SLEET_MORNING, is_day: 1},
    {id: 56, condition: weatherConditions.MODERATE_OR_HEAVY_SLEET, image: weatherBackground.SLEET_NIGHT, is_day: 0},
    {id: 57, condition: weatherConditions.PATCHY_LIGHT_SNOW, image: weatherBackground.SNOW_MORNING, is_day: 1},
    {id: 58, condition: weatherConditions.PATCHY_LIGHT_SNOW, image: weatherBackground.SNOW_NIGHT, is_day: 0},
    {id: 59, condition: weatherConditions.LIGHT_SNOW, image: weatherBackground.SNOW_MORNING, is_day: 1},
    {id: 60, condition: weatherConditions.LIGHT_SNOW, image: weatherBackground.SNOW_NIGHT, is_day: 0},
    {id: 61, condition: weatherConditions.PATCHY_MODERATE_SNOW, image: weatherBackground.SNOW_MORNING, is_day: 1},
    {id: 62, condition: weatherConditions.PATCHY_MODERATE_SNOW, image: weatherBackground.SNOW_NIGHT, is_day: 0},
    {id: 63, condition: weatherConditions.MODERATE_SNOW, image: weatherBackground.SNOW_MORNING, is_day: 1},
    {id: 64, condition: weatherConditions.MODERATE_SNOW, image: weatherBackground.SNOW_NIGHT, is_day: 0},
    {id: 65, condition: weatherConditions.PATCHY_HEAVY_SNOW, image: weatherBackground.SNOW_MORNING, is_day: 1},
    {id: 66, condition: weatherConditions.PATCHY_HEAVY_SNOW, image: weatherBackground.SNOW_NIGHT, is_day: 0},
    {id: 67, condition: weatherConditions.HEAVY_SNOW, image: weatherBackground.SNOW_MORNING, is_day: 1},
    {id: 68, condition: weatherConditions.HEAVY_SNOW, image: weatherBackground.SNOW_NIGHT, is_day: 0},
    {id: 69, condition: weatherConditions.ICE_PALLETS, image: weatherBackground.ICE_PALLETS_MORNING, is_day: 1},
    {id: 70, condition: weatherConditions.ICE_PALLETS, image: weatherBackground.ICE_PALLETS_NIGHT, is_day: 0},
    {id: 71, condition: weatherConditions.LIGHT_RAIN_SHOWER, image: weatherBackground.RAIN_SHOWER_MORNING, is_day: 1},
    {id: 72, condition: weatherConditions.LIGHT_RAIN_SHOWER, image: weatherBackground.RAIN_SHOWER_NIGHT, is_day: 0},
    {id: 73, condition: weatherConditions.MODERATE_OR_HEAVY_RAIN_SHOWER, image: weatherBackground.RAIN_SHOWER_MORNING, is_day: 1},
    {id: 74, condition: weatherConditions.MODERATE_OR_HEAVY_RAIN_SHOWER, image: weatherBackground.RAIN_SHOWER_NIGHT, is_day: 0},
    {id: 75, condition: weatherConditions.TORRENTIAL_RAIN_SHOWER, image: weatherBackground.RAIN_SHOWER_MORNING, is_day: 1},
    {id: 76, condition: weatherConditions.TORRENTIAL_RAIN_SHOWER, image: weatherBackground.RAIN_SHOWER_NIGHT, is_day: 0},
    {id: 77, condition: weatherConditions.LIGHT_SLEET_SHOWER, image: weatherBackground.SLEET_MORNING, is_day: 1},
    {id: 78, condition: weatherConditions.LIGHT_SLEET_SHOWER, image: weatherBackground.SLEET_NIGHT, is_day: 0},
    {id: 79, condition: weatherConditions.MODERATE_OR_HEAVY_SLEET_SHOWER, image: weatherBackground.SLEET_MORNING, is_day: 1},
    {id: 80, condition: weatherConditions.MODERATE_OR_HEAVY_SLEET_SHOWER, image: weatherBackground.SLEET_NIGHT, is_day: 0},
    {id: 81, condition: weatherConditions.LIGHT_SNOW_SHOWER, image: weatherBackground.SNOW_MORNING, is_day: 1},
    {id: 82, condition: weatherConditions.LIGHT_SNOW_SHOWER, image: weatherBackground.SNOW_NIGHT, is_day: 0},
    {id: 83, condition: weatherConditions.MODERATE_OR_HEAVY_SNOW_SHOWER, image: weatherBackground.SNOW_MORNING, is_day: 1},
    {id: 84, condition: weatherConditions.MODERATE_OR_HEAVY_SNOW_SHOWER, image: weatherBackground.SNOW_NIGHT, is_day: 0},
    {id: 85, condition: weatherConditions.LIGHT_SHOWERS_OF_ICE_PALLETS, image: weatherBackground.ICE_PALLETS_MORNING, is_day: 1},
    {id: 86, condition: weatherConditions.LIGHT_SHOWERS_OF_ICE_PALLETS, image: weatherBackground.ICE_PALLETS_NIGHT, is_day: 0},
    {id: 87, condition: weatherConditions.MODERATE_OR_HEAVY_SHOWERS_OF_ICE_PALLETS, image: weatherBackground.ICE_PALLETS_MORNING, is_day: 1},
    {id: 88, condition: weatherConditions.MODERATE_OR_HEAVY_SHOWERS_OF_ICE_PALLETS, image: weatherBackground.ICE_PALLETS_NIGHT, is_day: 0},
    {id: 89, condition: weatherConditions.PATCHY_LIGHT_RAIN_WITH_THUNDER, image: weatherBackground.LIGHT_RAIN_WITH_THUNDER_MORN_NIGHT, is_day: 1},
    {id: 90, condition: weatherConditions.PATCHY_LIGHT_RAIN_WITH_THUNDER, image: weatherBackground.LIGHT_RAIN_WITH_THUNDER_MORN_NIGHT, is_day: 0},
    {id: 91, condition: weatherConditions.MODERATE_OR_HEAVY_LIGHT_RAIN_WITH_THUNDER, image: weatherBackground.RAIN_SNOW_WITH_THUNDER_MORNING, is_day: 1},
    {id: 92, condition: weatherConditions.MODERATE_OR_HEAVY_LIGHT_RAIN_WITH_THUNDER, image: weatherBackground.RAIN_SNOW_WITH_THUNDER_NIGHT, is_day: 0},
    {id: 93, condition: weatherConditions.MODERATE_OR_HEAVY_LIGHT_SNOW_WITH_THUNDER, image: weatherBackground.RAIN_SNOW_WITH_THUNDER_MORNING, is_day: 1},
    {id: 94, condition: weatherConditions.MODERATE_OR_HEAVY_LIGHT_SNOW_WITH_THUNDER, image: weatherBackground.RAIN_SNOW_WITH_THUNDER_NIGHT, is_day: 0},
]

export const WEATHER_BACKGROUND_OLD = [
	
	{
		id : 1273,
		"day" : "Patchy light rain with thunder",
		"night" : "Patchy light rain with thunder",
		"icon" : 386
	},
	{
		id : 1276,
		"day" : "Moderate or heavy rain with thunder",
		"night" : "Moderate or heavy rain with thunder",
		"icon" : 389
	},
	{
		id : 1279,
		"day" : "Patchy light snow with thunder",
		"night" : "Patchy light snow with thunder",
		"icon" : 392
	},
	{
		id : 1282,
		"day" : "Moderate or heavy snow with thunder",
		"night" : "Moderate or heavy snow with thunder",
		"icon" : 395
	}
]
